openapi: 3.0.4

info:
  title: AlgaShop - Ordering API
  version: "1.0"

servers:
  - description: Development
    url: http://localhost:8080
  - description: Production
    url: https://api.algashop.com.br

paths:
  /api/v1/customers:
    post:
      description: Register a new customer
      tags:
        - Customers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerInput'
      responses:
        201:
          description: Customer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          headers:
            Location:
              schema:
                type: string
              description: 'URL of the created customer'
              example: '/api/v1/customers/0199675d-e16f-70c5-932e-207998e5e1b4'
        400:
          $ref: '#/components/responses/BadRequest'
        409:
          $ref: '#/components/responses/Conflict'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'
    get:
      description: List all customers
      tags:
        - Customers
      parameters:
        - name: document
          in: query
          schema:
            type: string
            example: "12345"
          required: false
        - name: email
          in: query
          schema:
            type: string
            example: "customer@example.com"
          required: false
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
        - $ref: '#/components/parameters/sort'
        - $ref: '#/components/parameters/direction'
      responses:
        200:
          description: A list of customers
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - type: object
                    properties:
                      content:
                        type: array
                        items:
                          $ref: '#/components/schemas/Customer'
  /api/v1/customers/{customerId}:
    get:
      description: Get customer details by ID
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          example: "0199675d-e16f-70c5-932e-207998e5e1b4"
      responses:
        200:
          description: Customer details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        404:
          $ref: '#/components/responses/NotFound'
    put:
      description: Update customer details by ID
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          example: "0199675d-e16f-70c5-932e-207998e5e1b4"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerUpdateInput'
      responses:
        200:
          description: Customer details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          $ref: '#/components/responses/Conflict'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'
    delete:
      description: Delete customer by ID
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          example: "0199675d-e16f-70c5-932e-207998e5e1b4"
      responses:
        204:
          description: 'Customer deleted successfully'
        404:
          $ref: '#/components/responses/NotFound'

components:
  parameters:
    page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        default: 0
        example: 2
    size:
      name: size
      in: query
      required: false
      schema:
        type: integer
        default: 10
        example: 10
    sort:
      name: sortByProperty
      in: query
      required: false
      schema:
        type: string
        example: "firstName"
    direction:
      name: sortDirection
      in: query
      required: false
      schema:
        type: string
        enum:
          - ASC
          - DESC
        example: "ASC"
  responses:
    BadRequest:
      description: 'Invalid request'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
    NotFound:
      description: 'Resource not found'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
    Conflict:
      description: 'Conflict - e.g., resource already exists'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
    UnprocessableEntity:
      description: 'Unprocessable Entity - e.g., validation errors'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
    InternalServerError:
      description: 'Internal server error'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
  schemas:
    Customer:
      type: object
      required:
        - id
        - firstName
        - lastName
        - email
        - document
        - phone
        - birthDate
        - loayaltyPoints
        - registeredAt
        - promotionNotificationsAllowed
        - archived
        - address
      properties:
        id:
          type: string
          format: uuid
          example: "0199675d-e16f-70c5-932e-207998e5e1b4"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        email:
          type: string
          format: email
          example: "johndoe@example.com"
        document:
          type: string
          example: "12345"
        phone:
          type: string
          example: "1191234564"
        birthDate:
          type: string
          format: date
          example: "1990-01-01"
        loayaltyPoints:
          type: integer
          example: 100
        registeredAt:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
        archivedAt:
          type: string
          format: date-time
          example: "2023-12-01T12:00:00Z"
        promotionNotificationsAllowed:
          type: boolean
          example: false
        archived:
          type: boolean
          example: false
        address:
          $ref: '#/components/schemas/Address'
    Address:
      type: object
      required:
        - street
        - number
        - neighborhood
        - city
        - state
        - zipCode
      properties:
            street:
              type: string
              example: "123 Main St"
              nullable: false
              x-validation: "notBlank"
            number:
              type: string
              example: "100"
              nullable: false
              x-validation: "notBlank"
            complement:
              type: string
              example: "Apt 4B"
              nullable: true
            neighborhood:
              type: string
              example: "Downtown"
              nullable: false
              x-validation: "notBlank"
            city:
              type: string
              example: "Springfield"
              nullable: false
              x-validation: "notBlank"
            state:
              type: string
              example: "South Carolina"
              nullable: false
              x-validation: "notBlank"
            zipCode:
              type: string
              example: "62701"
              nullable: false
              x-validation: "notBlank"
    CustomerInput:
      type: object
      required:
        - firstName
        - lastName
        - email
        - document
        - phone
        - birthDate
        - promotionNotificationsAllowed
        - address
      properties:
        firstName:
          type: string
          example: "John"
          nullable: false
          x-validation: "notBlank"
        lastName:
          type: string
          example: "Doe"
          nullable: false
          x-validation: "notBlank"
        email:
          type: string
          format: email
          example: "johndoe@example.com"
          nullable: false
          x-validation: ["notBlank", "email"]
        document:
          type: string
          example: "12345"
          nullable: false
          x-validation: "notBlank"
        phone:
          type: string
          example: "1191234564"
          nullable: false
          x-validation: "notBlank"
        birthDate:
          type: string
          format: date
          example: "1990-01-01"
          x-validation: "pastDate"
        promotionNotificationsAllowed:
          type: boolean
          example: false
          nullable: false
        address:
          $ref: '#/components/schemas/Address'
    CustomerUpdateInput:
      type: object
      required:
        - firstName
        - lastName
        - phone
        - promotionNotificationsAllowed
        - address
      properties:
        firstName:
          type: string
          example: "John"
          nullable: false
          x-validation: "notBlank"
        lastName:
          type: string
          example: "Doe"
          nullable: false
          x-validation: "notBlank"
        phone:
          type: string
          example: "1191234564"
          nullable: false
          x-validation: "notBlank"
        promotionNotificationsAllowed:
          type: boolean
          example: false
          nullable: false
        address:
          $ref: '#/components/schemas/Address'
    ProblemDetail:
      type: object
      required:
        - status
        - type
      properties:
        status:
          type: integer
          format: int32
          example: 400
        type:
          type: string
          format: uri
          example: "https://example.com/probs/out-of-credit"
        title:
          type: string
          example: "You do not have enough credit."
        instance:
          type: string
          format: uri
          example: "/api/v1/customers"
        detail:
          type: string
          example: "Your current balance is 30, but that costs 50."
        timestamp:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
        fields:
          type: object
          description: "List of fields with validation errors"
    Page:
      type: object
      required:
        - content
        - size
        - number
        - totalElements
        - totalPages
      properties:
        number:
          type: integer
          example: 2
        size:
          type: integer
          example: 10
        totalElements:
          type: integer
          example: 100
        totalPages:
          type: integer
          example: 10
    