openapi: 3.0.4

info:
  title: AlgaShop - Ordering API
  version: "1.0"

servers:
  - description: Development
    url: http://localhost:8080
  - description: Production
    url: https://api.algashop.com.br

paths:
  /api/v1/customers:
    post:
      description: Register a new customer
      tags:
        - Customers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerInput'
      responses:
        201:
          description: Customer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          headers:
            Location:
              schema:
                type: string
              description: 'URL of the created customer'
              example: '/api/v1/customers/0199675d-e16f-70c5-932e-207998e5e1b4'
        400:
          $ref: '#/components/responses/BadRequest'
        409:
          $ref: '#/components/responses/Conflict'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'
    get:
      description: List all customers
      tags:
        - Customers
      parameters:
        - name: document
          in: query
          schema:
            type: string
            example: "12345"
          required: false
        - name: email
          in: query
          schema:
            type: string
            example: "customer@example.com"
          required: false
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
        - $ref: '#/components/parameters/sort'
        - $ref: '#/components/parameters/direction'
      responses:
        200:
          description: A list of customers
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Page'
                  - type: object
                    properties:
                      content:
                        type: array
                        items:
                          $ref: '#/components/schemas/CustomerSummary'
  /api/v1/customers/{customerId}:
    get:
      description: Get customer details by ID
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          example: "0199675d-e16f-70c5-932e-207998e5e1b4"
      responses:
        200:
          description: Customer details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        404:
          $ref: '#/components/responses/NotFound'
    put:
      description: Update customer details by ID
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          example: "0199675d-e16f-70c5-932e-207998e5e1b4"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerUpdateInput'
      responses:
        200:
          description: Customer details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          $ref: '#/components/responses/Conflict'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'
    delete:
      description: Delete customer by ID
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
          example: "0199675d-e16f-70c5-932e-207998e5e1b4"
      responses:
        204:
          description: 'Customer deleted successfully'
        404:
          $ref: '#/components/responses/NotFound'

  /api/v1/orders:
    post:
      tags:
        - Orders
      description: Create a new order
      requestBody:
        required: true
        content:
          application/vnd.order-with-shopping-cart.v1+json:
            schema:
              $ref: '#/components/schemas/OrderWithShoppingCartInput'
          application/vnd.order-with-product.v1+json:
            schema:
              $ref: '#/components/schemas/OrderWithProductInput'
      responses:
        201:
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          headers:
            Location:
              schema:
                type: string
              description: 'URL of the created order'
              example: '/api/v1/orders/0N4E3KAHJ6Y67'
        400:
          $ref: '#/components/responses/BadRequest'
        409:
          $ref: '#/components/responses/Conflict'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'
            

components:
  parameters:
    page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        default: 0
        example: 2
    size:
      name: size
      in: query
      required: false
      schema:
        type: integer
        default: 10
        example: 10
    sort:
      name: sortByProperty
      in: query
      required: false
      schema:
        type: string
        example: "firstName"
    direction:
      name: sortDirection
      in: query
      required: false
      schema:
        type: string
        enum:
          - ASC
          - DESC
        example: "ASC"
  responses:
    BadRequest:
      description: 'Invalid request'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
    NotFound:
      description: 'Resource not found'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
    Conflict:
      description: 'Conflict - e.g., resource already exists'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
    UnprocessableEntity:
      description: 'Unprocessable Entity - e.g., validation errors'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
    InternalServerError:
      description: 'Internal server error'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
  schemas:
    Customer:
      type: object
      required:
        - id
        - firstName
        - lastName
        - email
        - document
        - phone
        - birthDate
        - loayaltyPoints
        - registeredAt
        - promotionNotificationsAllowed
        - archived
        - address
      properties:
        id:
          type: string
          format: uuid
          example: "0199675d-e16f-70c5-932e-207998e5e1b4"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        email:
          type: string
          format: email
          example: "johndoe@example.com"
        document:
          type: string
          example: "12345"
        phone:
          type: string
          example: "1191234564"
        birthDate:
          type: string
          format: date
          example: "1990-01-01"
        loayaltyPoints:
          type: integer
          example: 100
        registeredAt:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
        archivedAt:
          type: string
          format: date-time
          example: "2023-12-01T12:00:00Z"
        promotionNotificationsAllowed:
          type: boolean
          example: false
        archived:
          type: boolean
          example: false
        address:
          $ref: '#/components/schemas/Address'
    CustomerSummary:
      type: object
      required:
        - id
        - firstName
        - lastName
        - email
        - phone
        - archived
      properties:
        id:
          type: string
          format: uuid
          example: "0199675d-e16f-70c5-932e-207998e5e1b4"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        email:
          type: string
          format: email
          example: "johndoe@example.com"
        phone:
          type: string
          example: "1191234564"
        archived:
          type: boolean
          example: false
    CustomerInput:
      type: object
      required:
        - firstName
        - lastName
        - email
        - document
        - phone
        - birthDate
        - promotionNotificationsAllowed
        - address
      properties:
        firstName:
          type: string
          example: "John"
          nullable: false
          x-validation: "notBlank"
        lastName:
          type: string
          example: "Doe"
          nullable: false
          x-validation: "notBlank"
        email:
          type: string
          format: email
          example: "johndoe@example.com"
          nullable: false
          x-validation: ["notBlank", "email"]
        document:
          type: string
          example: "12345"
          nullable: false
          x-validation: "notBlank"
        phone:
          type: string
          example: "1191234564"
          nullable: false
          x-validation: "notBlank"
        birthDate:
          type: string
          format: date
          example: "1990-01-01"
          x-validation: "pastDate"
        promotionNotificationsAllowed:
          type: boolean
          example: false
          nullable: false
        address:
          $ref: '#/components/schemas/Address'
    CustomerUpdateInput:
      type: object
      required:
        - firstName
        - lastName
        - phone
        - promotionNotificationsAllowed
        - address
      properties:
        firstName:
          type: string
          example: "John"
          nullable: false
          x-validation: "notBlank"
        lastName:
          type: string
          example: "Doe"
          nullable: false
          x-validation: "notBlank"
        phone:
          type: string
          example: "1191234564"
          nullable: false
          x-validation: "notBlank"
        promotionNotificationsAllowed:
          type: boolean
          example: false
          nullable: false
        address:
          $ref: '#/components/schemas/Address'
    Address:
      type: object
      required:
        - street
        - number
        - neighborhood
        - city
        - state
        - zipCode
      properties:
            street:
              type: string
              example: "123 Main St"
              nullable: false
              x-validation: "notBlank"
            number:
              type: string
              example: "100"
              nullable: false
              x-validation: "notBlank"
            complement:
              type: string
              example: "Apt 4B"
              nullable: true
            neighborhood:
              type: string
              example: "Downtown"
              nullable: false
              x-validation: "notBlank"
            city:
              type: string
              example: "Springfield"
              nullable: false
              x-validation: "notBlank"
            state:
              type: string
              example: "South Carolina"
              nullable: false
              x-validation: "notBlank"
            zipCode:
              type: string
              example: "62701"
              nullable: false
              x-validation: "notBlank"
    ProblemDetail:
      type: object
      required:
        - status
        - type
      properties:
        status:
          type: integer
          format: int32
          example: 400
        type:
          type: string
          format: uri
          example: "https://example.com/probs/out-of-credit"
        title:
          type: string
          example: "You do not have enough credit."
        instance:
          type: string
          format: uri
          example: "/api/v1/customers"
        detail:
          type: string
          example: "Your current balance is 30, but that costs 50."
        timestamp:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
        fields:
          type: object
          description: "List of fields with validation errors"
    Page:
      type: object
      required:
        - content
        - size
        - number
        - totalElements
        - totalPages
      properties:
        number:
          type: integer
          example: 2
        size:
          type: integer
          example: 10
        totalElements:
          type: integer
          example: 100
        totalPages:
          type: integer
          example: 10
    OrderWithProductInput:
      required:
        - customerId
        - paymentMethod
        - productId
        - quantity
        - shipping
        - billing
      properties:
        customerId:
          type: string
          example: "6e148bd5-47f6-4022-b9da-07cfaa294f7a"
          nullable: false
        productId:
          type: string
          example: "28fcd9fb-4ce7-44d6-9583-14d8b3dc5aff"
          nullable: false
        quantity:
          type: integer
          example: 12
          nullable: false
          x-validation: "positive"
        paymentMethod:
          type: string
          example: "GATEWAY_BALANCE"
          nullable: false
        shipping:
          $ref: "#/components/schemas/ShippingInput"
        billing:
          $ref: "#/components/schemas/Billing"
    OrderWithShoppingCartInput:
      required:
        - shoppingCartId
        - paymentMethod
        - shipping
        - billing
      properties:
        shoppingCartId:
          type: string
          example: "28fcd9fb-4ce7-44d6-9583-14d8b3dc5aff"
          nullable: false
        paymentMethod:
          type: string
          example: "GATEWAY_BALANCE"
          nullable: false
        shipping:
          $ref: "#/components/schemas/ShippingInput"
        billing:
          $ref: "#/components/schemas/Billing"
    Order:
      required:
        - id
        - customer
        - paymentMethod
        - totalItems
        - totalAmount
        - placedAt
        - canceledAt
        - paidAt
        - readyAt
        - status
        - items
        - shipping
        - billing
      properties:
        id:
          type: string
          example: "01226N0640J7Q"
        customer:
          $ref: "#/components/schemas/CustomerMinimal"
        totalItems:
          type: integer
          example: 2
        totalAmount:
          type: number
          example: 41.98
        placedAt:
          type: string
          format: date-time
          example: "2024-04-04T00:12:45Z"
        canceledAt:
          type: string
          format: date-time
          example: "2024-04-04T00:12:45Z"
        paidAt:
          type: string
          format: date-time
          example: "2024-04-04T00:12:45Z"
        readyAt:
          type: string
          format: date-time
          example: "2024-04-04T00:12:45Z"
        status:
          type: string
          example: "PAID"
        paymentMethod:
          type: string
          example: "GATEWAY_BALANCE"
        shipping:
          $ref: "#/components/schemas/Shipping"
        billing:
          $ref: "#/components/schemas/Billing"
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"
    OrderItem:
      required:
        - id
        - productId
        - productName
        - quantity
        - price
        - totalAmount
      properties:
        id:
          type: string
          example: "02226N0640J7F"
        productId:
          type: string
          example: "28fcd9fb-4ce7-44d6-9583-14d8b3dc5aff"
        price:
          type: number
          example: 19.99
          format: double
          minimum: 1
          maximum: 100000
        productName:
          type: string
          example: "Notebook Dive Gamer X11"
        quantity:
          type: integer
          example: 2
          minimum: 1
          maximum: 100
        totalAmount:
          type: number
          example: 19.99
          format: double
          minimum: 1
          maximum: 100000
    ShippingInput:
      type: object
      properties:
        recipient:
          $ref: "#/components/schemas/Recipient"
        address:
          $ref: "#/components/schemas/Address"
    Recipient:
      type: object
      required:
        - firstName
        - lastName
        - document
        - phone
        - address
      properties:
        firstName:
          type: string
          example: "John"
          nullable: false
        lastName:
          type: string
          example: "Doe"
          nullable: false
        document:
          type: string
          example: "12345"
          nullable: false
        phone:
          type: string
          example: "5511912341234"
          nullable: false
    Billing:
      type: object
      required:
        - firstName
        - lastName
        - document
        - phone
        - email
        - address
      properties:
        firstName:
          type: string
          example: "John"
          nullable: false
        lastName:
          type: string
          example: "Doe"
          nullable: false
        document:
          type: string
          example: "12345"
          nullable: false
        phone:
          type: string
          example: "5511912341234"
          nullable: false
        email:
          type: string
          example: "johndoe@email.com"
          nullable: false
        address: 
          $ref: "#/components/schemas/Address"
    Shipping:
      type: object
      required:
        - cost
        - expectedDate
        - recipient
        - address
      properties:
        cost:
          type: number
          example: 20.50
        expectedDate:
          type: string
          format: date
          example: "2026-05-01"
        recipient:
          $ref: "#/components/schemas/Recipient"
        address:
          $ref: "#/components/schemas/Address"
    CustomerMinimal:
      type: object
      required:
        - id
        - firstName
        - lastName
        - document
        - email
        - phone
        - archived
      properties:
        id: 
          type: string
          example: "380d7e70-7942-4b8d-a0e9-b93d79aa6745"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        document:
          type: string
          example: "12345"
        email:
          type: string
          example: "johndoe@email.com"
        phone:
          type: string
          example: "1191234564"
    